services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tb-carecom-frontend
    ports:
      - "5173:80"  # ini sudah betul
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # ⬅️ mount SSL certs ke dalam container
    restart: unless-stopped
    networks:
      - tb-carecom-network
