services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tb-carecom-frontend
    ports:
      - "5173:80"  # <- ini yang benar! port host 5173 -> container 80
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - tb-carecom-network

networks:
  tb-carecom-network:
    driver: bridge
