version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tb-carecom-frontend
    expose:
      - "5173"  # expose internal, tidak publish keluar
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - tb-carecom-network

    nginx:
    image: nginx:latest
    container_name: tb-carecom-nginx
    depends_on:
      - frontend
    ports:
      - "8080:80"     # HTTP internal
      - "8443:443"    # HTTPS external (bisa dipakai Cloudflare)
    volumes:
      - ./nginx.simple.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - tb-carecom-network


networks:
  tb-carecom-network:
    driver: bridge
